const SUBJECT_CATEGORIES = {
  "Common / First Year": [
    "Accounting for Engineers", "Applied Chemistry for Engineers", "Applied Physics for Engineers",
    "Basic Electrical Technology", "Basic Electronics", "Basic Mechanical Engineering",
    "Biology for Engineers", "Communication Skills in English", "Computational Mathematics - 1",
    "Computational Mathematics - 2", "Computer Aided Engineering Graphics", "Data Visualization",
    "Engineering Chemistry", "Engineering Graphics - 1", "Engineering Graphics - 2",
    "Engineering Mathematics - 1", "Engineering Mathematics - 2", "Engineering Mechanics and Smart Buildings",
    "Engineering Physics", "Environmental Studies", "Fundamentals of Electrical Engineering",
    "Fundamentals of Electronics", "Fundamentals of Mechanical Engineering",
    "Introduction to Object Oriented Programming", "Mechanics of Solids", "Problem Solving Using Computers",
    "Programming for Problem Solving"
  ],
  "Computer Science / AI / IT / Data": [
    "Advanced Numerical Methods", "Advanced Programming", "Algebraic Structures",
    "Algorithms & Data Structures", "Artificial Intelligence", "Artificial Neural Network",
    "Big Data Analytics", "Big Data Analytics and Tools", "Capital Markets Technology",
    "Compiler Design", "Computer Networks", "Computational Linear Algebra", "Cyber Security",
    "Data Analytics", "Data Communication and Computer Networks", "Data Communication and Networks",
    "Data Mining", "Data Structures", "Data Structures and Algorithms", "Database Management Systems",
    "Database Systems", "Deep Learning", "Deep Learning Techniques", "Design & Analysis of Algorithms",
    "Digital Logic Design", "Digital Systems and Computer Organization", "Discrete Mathematical Structures",
    "Discrete Mathematics", "Elementary Number Theory", "Embedded and Decentralized Finance",
    "Embedded System Design", "Embedded Systems Design and Programming", "Engineering Economics & Financial Management",
    "Engineering Economics and Financial Management", "Essentials of Management", "Financial Management",
    "Foundation of Computer Vision", "High Performance Computing", "Information Security",
    "Introduction to Artificial Intelligence", "Introduction to Banking, Payments and Capital Markets",
    "Introduction to Fintech", "Machine Learning", "Machine Learning & Deep Learning",
    "Mathematical Foundations for Data Science-III", "Mathematical Logic", "Mathematics for Finance",
    "Multivariate Analysis", "Network Programming and Advanced Communication Networks",
    "Object-Oriented Software Development", "Operating Systems", "Operations Research",
    "Parallel Computer Architecture and Programming", "Principles of Artificial Intelligence",
    "Principles of Cryptography", "Principles of Operating Systems", "Probability and Optimization",
    "Probability and Stochastic Process", "Probability, Stochastic Process and Operations Research",
    "Programming Paradigm", "Real Analysis", "Scientific Computing", "Software Application Design",
    "Software Engineering", "Statistics for Finance", "Time Series Analysis",
    "Vector Analysis and Complex Variables", "Web Programming", "Wireless Communication and Computing"
  ],
  "Electronics / Electrical / Embedded": [
    "Analog and Digital Communication", "Analog and Mixed Signal IC Design", "Analog Circuits",
    "Analog Electronic Circuits", "Analog Integrated Circuits", "Analog System Design",
    "Communication Networks", "Communication Systems", "Communication Techniques",
    "Computer Architecture and Organization", "Computer Organization and Architecture",
    "Cyber Physical System Design", "Digital Circuits", "Digital Circuits & System Design",
    "Digital Signal Processing", "Digital System Design", "Digital Transmission",
    "Electrical Circuit Analysis", "Electrical Machinery - I", "Electrical Machinery - II",
    "Electromagnetic Field Theory", "Electromagnetic Waves", "FPGA based System Design using Verilog",
    "Generation, Transmission & Distribution", "Industrial Automation & Drives", "Industrial Instrumentation",
    "Introduction of Cyber Physical Systems", "Introduction to Control Theory", "Linear Control Theory",
    "Linear Integrated Circuits", "Measurements & Instrumentation", "MEMS and NEMS", "Microcontroller",
    "Microcontrollers", "Microcontrollers and Embedded Systems", "Microprocessors", "Microwave Engineering",
    "Modern Control Theory", "Network Analysis", "Networks and Signals", "Power Electronics",
    "Power System Analysis", "Process Instrumentation and Control", "Sensor Technology",
    "Sensors and Transducers", "Signals & Systems", "Switchgear & Protection", "VLSI Design",
    "VLSI Fabrication Technology", "VLSI Testing", "Verification using System Verilog", "Wireless Communication"
  ],
  "Mechanical / Automobile / Aerospace": [
    "3D Printing and Design", "Advanced Aircraft Structures", "Aerodynamics & Propulsion",
    "Air-Breathing Propulsion", "Aircraft Design", "Aircraft Performance",
    "Automobile Engineering / Automotive Mechanics for Electric Vehicles", "Automotive Component Design",
    "Autotronics", "Avionics and Navigation System", "Basics of I C Engines", "CAD and Kinematics' Simulation",
    "Design of Machine Elements", "Digital and Analog CMOS Design", "Electric Drives", "Energy and Heat Transfer",
    "Engineering System Design", "Engineering Thermodynamics", "Finite Element Methods",
    "Flight Dynamics and Control", "Fluid Dynamics", "Fluid Mechanics", "Geometric Modelling",
    "Heat and Mass Transfer", "Heat Transfer", "Hydraulics and Pneumatics Systems",
    "Incompressible Aerodynamics", "Industrial Automation", "Industrial Automation and Robotics",
    "Industrial Internet of Things", "Introduction to Aerospace Engineering", "Introduction to Aircraft Structures",
    "Lean Manufacturing and Six Sigma", "Manufacturing Processes-I", "Manufacturing Processes - II",
    "Manufacturing Technology / Foundations of EV and Hybrid Vehicles", "Materials Engineering",
    "Materials Science and Metallurgy", "Materials and Processing Techniques", "Mechanics of Materials",
    "Mechanics of Robotics Systems", "Metrology and Measurements", "Microcontroller based System Design",
    "Robot Operating System", "Strength of Materials", "Supply and Logistics Management", "Theory of Machines",
    "Thermal Engineering", "Turbomachines", "Vehicle Chassis Systems", "Vehicle Dynamics and Control",
    "Vehicle Transmission Systems", "Work System Engineering and Ergonomics"
  ],
  "Civil / Chemical / Biotech / Biomedical": [
    "Anatomy and Physiology", "Animal and Plant Biotechnology", "Applied Soil Engineering",
    "Basic Clinical Science II", "Basic Clinical Sciences I", "Basic Reinforced Concrete Design",
    "Basic Structural Steel Design", "Biochemistry", "Biomechanics", "Biomedical Instrumentation",
    "Biomaterials", "Bioethics and Intellectual Property Rights", "Bioinformatics", "Bioprocess Calculations",
    "Bioprocess Engineering", "Bioreaction Engineering", "Building Materials", "Cell and Molecular Biology",
    "Chemical Engineering Thermodynamics", "Chemical Process Calculations", "Chemical Reaction Engineering",
    "Chemical and Biochemical Engineering Thermodynamics", "Compressible Aerodynamics", "Control Systems Engineering",
    "Design of Experiments", "Digital Image Processing", "Downstream Processes - I", "Downstream Processes - II",
    "Estimation, Costing and Project Management", "Fluid Flow Operations", "Genetic Engineering",
    "Geotechnical Engineering", "Immunology", "Lean Manufacturing and Six Sigma", "Mass Transfer I",
    "Mass Transfer - II", "Medical Devices", "Mechanics of Structures", "Microbiology", "Modeling and Simulation",
    "Momentum Transfer", "Operations Management", "Particle Technology", "Physical and Organic Chemistry",
    "Pollution Control and Safety in Chemical Industry", "Principles of Heat and Mass Transfer",
    "Process Design of Chemical Equipment", "Process Dynamics and Control", "Process Modelling and Simulation",
    "Simulation Modeling and Analysis", "Total Quality Management", "Transport Phenomena",
    "Transportation Engineering", "Unit Operations", "Wastewater Management", "Water Resource Engineering",
    "Water Supply Engineering"
  ],
  "Misc / Interdisciplinary": [
    "Data Analytics and Visualisation", "Management Research Methods"
  ]
};

module.exports = SUBJECT_CATEGORIES;
